<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostsFromCategory($category_id = null)
    {
        $qb = $this->createQueryBuilder('p');

        if($category_id)
        {
            $qb->andWhere('p.category = :category_id')
              ->setParameter('category_id', $category_id);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
    
    public function getPostsFromTag($tag_id = null)
    {
        $qb = $this->createQueryBuilder('p');

        if($tag_id)
        {
            $qb->innerJoin('p.tags', 'pt')
              ->where('pt.id = :tag_id')
              ->setParameter('tag_id', $tag_id);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
