blog_admin_post:
    resource: "@BlogAdminBundle/Resources/config/routing/post.yml"
    prefix:   /post

blog_admin_homepage:
    path:     /
    defaults: { _controller: BlogAdminBundle:Start:index }
