blog_post:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /blog

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Start:index }
    
blog_category:
    path:     /category/{slug}
    defaults: { _controller: BlogBundle:Category:show }
