blog_post:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /blog

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Start:index }
    
blog_category:
    path:     /category/{slug}/{page}
    defaults: { _controller: BlogBundle:Category:show, page: 1 }
    
blog_tag:
    path:     /tag/{slug}/{page}
    defaults: { _controller: BlogBundle:Tag:show, page: 1 }
    
blog_archive:
    path:     /archive/{year}/{month}
    defaults: { _controller: "BlogBundle:Post:archive" }
    
blog_archives_page:
    path:     /archive
    defaults: { _controller: "BlogBundle:Post:archivesPage" }
    
blog_author:
    path:     /author/{email}
    defaults: { _controller: "BlogBundle:Post:author" }
