# src/BlogAdminBundle/Resources/config/doctrine/Image.orm.yml
BlogAdminBundle\Entity\Image:
  type: entity
  #repositoryClass: BlogAdminBundle\Repository\ImageRepository
  table: image
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    image:
      type: string
      length: 255
      nullable: true
  manyToOne:
    post:
      targetEntity: Post
      inversedBy: images
      #cascade: [ persist ]
      joinColumn:
        name: post_id
        referencedColumnName: id