# src/BlogBundle/Resources/config/doctrine/Post.orm.yml
BlogBundle\Entity\Post:
  type: entity
  #repositoryClass: ShopBundle\Repository\PostRepository
  table: post
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    slug:
      type: string
      length: 255
    #content_head:
    #  type: text
    content:
      type: text
    author_email:
      type: string
      length: 255
    is_published:
      type: boolean
    #show_comment:
    #  type: boolean
    #enable_comment:
    #  type: boolean
    published_at:
      type: datetime
    updated_at:
      type: datetime
  oneToMany:
    comments:
      targetEntity: Comment
      mappedBy: post
      cascade: [ remove ]
  manyToMany:
    tags:
      targetEntity: Tag
      inversedBy: posts
      #cascade: [ persist ]
      joinTable:
        name: post_tag
        joinColumns:
          post_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setPublishedAtValue ] 
    preUpdate: [ setUpdatedAtValue ]